spring.application.name=skillmentor
spring.profiles.active=dev

# PostgreSQL Database Configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/skill_mentor_v3
spring.datasource.username=${USERNAME}
spring.datasource.password=${PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA/Hibernate Configuration
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect










